### ISSUE TITLE
Install problem on OSX

### ISSUE THREAD

**Issue by rgiordan** [JuliaAstro/WCSLIB.jl#3]
Hello,

I'm trying to install WCSLIB on a mac running 10.10.2.  I am new to Julia.  I'm trying to install WCSLIB and I get the below errors.  Any ideas what is going wrong?

Thanks in advance,
Ryan

julia> Pkg.add("WCSLIB")
julia> Pkg.build("WCSLIB")

... succesful compiler commands...

gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -c cel.c
ar r libwcs-4.23.a cel.o
ar: libwcs-4.23.a is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
ar: libwcs-4.23.a: Inappropriate file type or format
make[2]: *** [libwcs-4.23.a(cel.o)] Error 1

…many similar errors...

gcc -DHAVE_CONFIG_H -I. -I.. -g -O2 -c wcsutrn.c
ar r libwcs-4.23.a wcsutrn.o
ar: libwcs-4.23.a is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
ar: libwcs-4.23.a: Inappropriate file type or format
make[2]: *** [libwcs-4.23.a(wcsutrn.o)] Error 1
make[2]: Target `lib' not remade because of errors.
make[1]: *** [../C/libwcs-4.23.a] Error 2
cd .. && ./config.status
config.status: creating makedefs
config.status: creating wcslib.pc
config.status: creating wcsconfig.h
config.status: creating wcsconfig_f77.h
config.status: creating wcsconfig_tests.h
config.status: wcsconfig_tests.h is unchanged
config.status: creating wcsconfig_utils.h
config.status: wcsconfig_utils.h is unchanged

gcc -DHAVE_CONFIG_H -I.. -I../C -g -O2 -c cel_f.c
cel_f.c:64:5: error: function cannot return function type 'int (int *)'
int celini_(int *cel)

…many similar errors and failed install...

**Comment by kbarbary** [comment]
Thanks for reporting this. @nolta will probably know better, but I'll give this a go.

It looks like `libwcs-4.23.a` already exists at the first time `ar` is called, and for some reason is a "fat file" (containing more than one architecture target). It is unclear to me why `libwcs-4.23.a` already exists at this point for you: on my (linux) machine, it doesn't seem to:

```
...
gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -g -O2 -c cel.c
ar r libwcs-4.23.a cel.o
ar: creating libwcs-4.23.a
...
```

You might try cleaning the build and re-running it explicitly, just to make sure you get the same failure from a clean directory:
```
$ cd ~/.julia/v0.3/WCSLIB/deps/src/wcslib-4.23/C
$ make realclean
$ make
```

**Comment by rgiordan** [comment]
Thanks for the help!  Running make realclean fixes the fat problem, but the second problem is still there.  (The libwcs-4.23.a file already existed because of an earlier failed attempt to install WCSLIB.)  So the real error is this:

mkdir tmp && \
	     cd tmp && \
	     trap 'cd .. ; rm -f -r tmp' 0 1 2 3 15 ; \
	     ar x ../libwcs-PIC.a && \
	     gcc -fPIC -dynamiclib -single_module -compatibility_version 4 -current_version 4.23 -o libwcs.4.23.dylib *.o -L/usr/local/lib -L/opt/local/lib -L/sw/lib -lm  && \
	     mv libwcs.4.23.dylib ..
cd .. && ./config.status
config.status: creating makedefs
config.status: creating wcslib.pc
config.status: creating wcsconfig.h
config.status: creating wcsconfig_f77.h
config.status: creating wcsconfig_tests.h
config.status: wcsconfig_tests.h is unchanged
config.status: creating wcsconfig_utils.h
config.status: wcsconfig_utils.h is unchanged

gcc -DHAVE_CONFIG_H -I.. -I../C -g -O2 -c cel_f.c
cel_f.c:64:5: error: function cannot return function type 'int (int *)'
int celini_(int *cel)
    ^
cel_f.c:34:26: note: expanded from macro 'celini_'
#define celini_  F77_FUNC(celini,  CELINI)
                         ^
cel_f.c:67:34: error: use of undeclared identifier 'cel'
  return celini((struct celprm *)cel);
                                 ^
cel_f.c:72:5: error: function cannot return function type 'int (int *, const int
      *, const void *, const int *)'
int celput_(int *cel, const int *what, const void *value, const int *i)
    ^
cel_f.c:35:26: note: expanded from macro 'celput_'
#define celput_  F77_FUNC(celput,  CELPUT)
                         ^
cel_f.c:82:28: error: use of undeclared identifier 'cel'
  celp  = (struct celprm *)cel;
                           ^

.... and many pages of similar errors.  (LMK if you want the full output.)

Ryan

**Comment by kbarbary** [comment]
Hmmmm... this is a bit of a guess, but there might be a problem with the `F77_FUNC` macro. That macro seems to be generated during configuration. Can you check what it is? For me:

```
$ cd ~/.julia/v0.3/WCSLIB/deps/src/wcslib-4.23
$ grep F77_FUNC wcsconfig_f77.h
#define F77_FUNC(name,NAME) name ## _
```

-------

Fortunately, it seems like the problem is only with the Fortran wrapper, which is actually not needed, as far as I know. You might try adding the flag `--disable-fortran`  to the configure command in `deps/build.jl` (on line 21). E.g.:
```julia
                       @build_steps begin
                         `./configure --prefix=$prefix --disable-fortran`
                         `make install`
```

Then delete the install directories and make realclean again:
```
$ rm -rf ~/.julia/v0.3/WCSLIB/deps/usr
$ cd ~/.julia/v0.3/WCSLIB/deps/src/wcslib-4.23
$ make realclean
```
Then retry the build through Julia:

```julia
julia> Pkg.build("WCSLIB")
```

If that works we should probably update the build script permanently with the `--disable-fortran` flag (and possibly some other flags I noticed like `--without-cfitsio` and `--without-pgplot`).

**Comment by rgiordan** [comment]
Thanks for your continued help.  Responses inline:

> Hmmmm... this is a bit of a guess, but there might be a problem with the
> F77_FUNC macro. That macro seems to be generated during configuration.
> Can you check what it is? For me:
>
> $ cd ~/.julia/v0.3/WCSLIB/deps/src/wcslib-4.23
> $ grep F77_FUNC wcsconfig_f77.h
> #define F77_FUNC(name,NAME) name ## _
>
> It looks like it's not defined for me:

$ grep F77_FUNC wcsconfig_f77.h

/* #undef F77_FUNC */

> Fortunately, it seems like the problem is only with the Fortran wrapper,
> which is actually not needed, as far as I know.
>
I tried following your steps, and it does not build that way either.  The
error is below:

if [ ! -d
"/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/pkgconfig" ]
; then \

     /usr/bin/install -c -d -m 2775
/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/pkgconfig ; \

   fi

/usr/bin/install -c -m 444 wcslib.pc
/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/pkgconfig/wcslib.pc

===============================[ ERROR: WCSLIB
]================================


File
String["/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/libwcs.dylib"]
was not created successfully (Tried to run
SynchronousStepCollection({`./configure
--prefix=/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr
--disable-fortran`,`make install`},"","") )

while loading
/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/build.jl, in
expression starting on line 28


================================================================================


================================[ BUILD ERRORS
]================================


WARNING: WCSLIB had build errors.


 - packages with build errors remain installed in
/Users/ryangiordanonon-admin/.julia/v0.3

 - build the package(s) and all dependencies with `Pkg.build("WCSLIB")`

 - build a single package by running its `deps/build.jl` script


================================================================================

**Comment by kbarbary** [comment]
It's hard to see from this what the error was. At now you have it configured to not try to build the fortran wrappers. Next, I'd probably try to directly run `make` again from within `~/.julia/v0.3/WCSLIB/deps/src/wcslib-4.23`. Since it shouldn't try to build the fortran wrappers, you should get a different error and we can see what it is. Just to be safe, I'd probably clean and reconfigure:
```
$ make realclean
$ ./configure --disable-fortran
$ make
```

**Comment by rgiordan** [comment]
Sorry for the delay in responding.  I can successfully run configure and make install on the command line exactly julia is doing.  That is, these commands complete successfully in bash:

    ./configure --prefix=/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr --disable-fortran
    make install

However, Pkg.build("WCSLIB") still gives the above error.  Note that the error says

   File String["/Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/libwcs.dylib"] was not created successfully 

Indeed, that file is not there, though similarly named files are:

    $ ls /Users/ryangiordanonon-admin/.julia/v0.3/WCSLIB/deps/usr/lib/
    libwcs-4.23.a     libwcs.4.23.dylib libwcs.4.dylib    libwcs.a          pkgconfig

Does this help give any clue about where to look for the problem?

**Comment by kbarbary** [comment]
Looks like everything is built and installed correctly except the symbolic link `libwcs.dylib`, which should point to `libwcs.4.dylib`. Try
```
ln -s libwcs.4.dylib libwcs.dylib
```

**Comment by kbarbary** [comment]
PS: At least on the surface, both these problems seem to be in the build process in the C library WCSLIB. We should update to the latest version (4.25.1) to make sure the changes haven't already been fixed. (But I don't see any notes on this in the [changelog](http://www.atnf.csiro.au/people/mcalabre/WCS/CHANGES)). I'll do this.

If they're still a problem and others on OS X can reproduce, we should report them back to Mark C.

**Comment by rgiordan** [comment]
The symbolic link fixed it, and I'm good to go.  Thank you very much for the quick and insightful help!

**Comment by kbarbary** [comment]
Nice!
