### ISSUE TITLE
WCSLIB Build Fails in Master Branch v0.4

### ISSUE THREAD

**Issue by odysseus9672** [JuliaAstro/WCSLIB.jl#7]
I'm running Julia Version 0.4.0-dev+5307, Commit 5035c5c*, on x86_64-apple-darwin14.3.0. Pkg.add("WCSLIB") fails with the following message:

LoadError: File AbstractString["/Users/sean/.julia/v0.4/WCSLIB/deps/usr/lib/libwcs.dylib"] was not created successfully (Tried to run BinDeps.SynchronousStepCollection(Any[`./configure --prefix=/Users/sean/.julia/v0.4/WCSLIB/deps/usr --disable-fortran --without-cfitsio --without-pgplot`,`make install`],"","") )
while loading /Users/sean/.julia/v0.4/WCSLIB/deps/build.jl, in expression starting on line 29

The directory in question contains:
ls /Users/sean/.julia/v0.4/WCSLIB/deps/usr/lib/
libwcs-4.25.1.a     libwcs.4.dylib      pkgconfig
libwcs.4.25.1.dylib libwcs.a

At a guess, the script is supposed to make a symbolic link? I'm not seeing any errors in the actual build script, for what it's worth.

**Comment by kbarbary** [comment]
Sounds like the same problem as in #3 (see end of discussion). Try creating the symbolic link manually with `ln -s libwcs.4.dylib libwcs.dylib`.

**Comment by odysseus9672** [comment]
Yep, that fixed it. Not sure why the symlink wasn't created in the build process. The libwcs.4.dylib was a symlink, so maybe somebody changed it so that it was created instead of libwcs.dylib?

**Comment by odysseus9672** [comment]
I decided to test the package to make sure it worked beyond just loading, and here's the output:

Pkg.test("WCSLIB")
INFO: Testing WCSLIB
WARNING: uint8(x) is deprecated, use UInt8(x) instead.
 in depwarn at ./deprecated.jl:62
 in uint8 at deprecated.jl:49
 in wcsmodify at /Users/sean/.julia/v0.4/WCSLIB/test/../src/WCSLIB.jl:138
 in wcsprm at /Users/sean/.julia/v0.4/WCSLIB/test/../src/WCSLIB.jl:151
 in include at ./boot.jl:253
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:304
 in _start at ./client.jl:404
while loading /Users/sean/.julia/v0.4/WCSLIB/test/runtests.jl, in expression starting on line 5
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{Ptr{UInt8}}, ::ASCIIString)
This may have arisen from a call to the constructor Ptr{UInt8}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Ptr{T}}, ::UInt64)
  convert{T}(::Type{Ptr{T}}, ::Int64)
  ...
 in wcspih at /Users/sean/.julia/v0.4/WCSLIB/test/../src/WCSLIB.jl:206
 in include at ./boot.jl:253
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:304
 in _start at ./client.jl:404
while loading /Users/sean/.julia/v0.4/WCSLIB/test/runtests.jl, in expression starting on line 30

===============================[ ERROR: WCSLIB ]================================

failed process: Process(`/Users/sean/juliaLang/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/sean/.julia/v0.4/WCSLIB/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================

**Comment by kbarbary** [comment]
This should be fixed on WCSLIB master. (See #5.)

**Comment by odysseus9672** [comment]
How do I switch to master?

**Comment by kbarbary** [comment]
http://julia.readthedocs.org/en/release-0.3/manual/packages/#checkout-pin-and-free

**Comment by odysseus9672** [comment]
Thanks, that fixes the tests, but I still had to manually add the symlink.

**Comment by odysseus9672** [comment]
I no longer have to manually add the symlink. I think it's safe to mark this issue closed.

**Comment by kbarbary** [comment]
Huh, I wonder what changed? Glad it's fixed though!
