### ISSUE TITLE
Is wcss2p 0- or 1-indexed?

### ISSUE THREAD

**Issue by rgiordan** [JuliaAstro/WCSLIB.jl#8]
Unlike most other languages used for astronomy, Julia is 1-indexed.  This makes me wonder whether the julia library function WCSLIB.wcss2p() returns 1- or 0-based pixel indices.

I can't seem to find the indexing of the C++ library documented anywhere either.

**Comment by rgiordan** [comment]
An astronomer colleague tells me that it is 1-indexed.

**Comment by kbarbary** [comment]
Probably to coincide with the FITS/WCS standard, which follows FORTRAN. This is a nice side benefit to using Julia in Astronomy. Maybe you could add a sentence to the docs or comments in the code?
